# Generated by Django 5.2.7 on 2025-10-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentfetch', '0002_userintereststock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(db_index=True, max_length=255)),
                ('comment', models.TextField()),
                ('source', models.CharField(blank=True, max_length=50)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
